### ISSUE TITLE
Navigation buttons overlap

### ISSUE THREAD

**Issue by laurensvanochten** [getgrav/grav-theme-receptar#1]
Just had a peek at the theme, looks great!

One thing that seems off is that hte navigation buttons for the image slider on the top are overlapping.

changing z-index solves it.

```
.slider-nav {
    z-index: 0;
}
```

**Comment by hexplor** [comment]
Thanks. Trying to replicate. Can you show me a screenshot or link where buttons overlaps ? Thanks

**Comment by laurensvanochten** [comment]
![screen shot 2016-01-19 at 14 08 47](https://cloud.githubusercontent.com/assets/16606366/12419408/3b080b5a-beb6-11e5-9a3f-89e0a49dc01f.png)

Hope you can see it on the above screenshot!

**Comment by hexplor** [comment]
Ah yes.. :) It appears that it's firefox only issue :)
