### ISSUE TITLE
Site title and description

### ISSUE THREAD

**Issue by dejalynn** [getgrav/grav-theme-receptar#3]
New to grav.  Started with the receptar skeleton.  After updating receptar to v1.1 the site title and site description defined in user/config/site.yaml no longer display.  Site title displays as "My Blog" and description displays default text as well.  Unsure of what other relevant info I can post to assist in debugging.

**Comment by flaviocopes** [comment]
Looking at https://github.com/getgrav/grav-theme-receptar/commit/abbfb6737cbf3deb89ff24f58effcb9b39fe28c2 you need to put them in user/languages/en.yaml : `SITE.TITLE`, `SITE.DESCRIPTION`. Didn't try, but that should help
